services:
  satisfactory-server:
    container_name: satisfactory-server
    hostname: satisfactory-server
    image: 'wolveix/satisfactory-server:latest'
    network_mode: host
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    volumes:
      - '/mnt/disk1/appdata/docker/satisfactory/config:/config'
    environment:
      - MAXPLAYERS=10
      - PGID=1000
      - PUID=1000
      - ROOTLESS=false
      - STEAMBETA=false
      - AUTOSAVEINTERVAL=60
      - AUTOSAVEONDISCONNECT=true
      - CRASHREPORT=true
      - MAXTICKRATE=60
    restart: always
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G
