services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8090
      - QBT_WEBUI_USERNAME=admin
      - QBT_WEBUI_PASSWORD=${QBT_WEBUI_PASSWORD}
    volumes:
      - /mnt/3TB/docker/Data/qbittorrent/config:/config
      - /mnt/NAS/Media/:/downloads
    ports:
      - "8090:8090"
    restart: unless-stopped
    networks:
      - backend

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
      - NZBGET_USER=${NZB_USER}
      - NZBGET_PASS=${NZB_PASS}
    volumes:
      - /mnt/3TB/docker/Data/nzbget/config:/config
      - /mnt/NAS/Media/:/downloads
    ports:
      - "6789:6789"
    restart: unless-stopped
    networks:
      - backend

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /mnt/3TB/docker/Data/prowlarr/config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped
    networks:
      - backend

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /mnt/3TB/docker/Data/sonarr/config:/config
      - /mnt/NAS/Media/:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - prowlarr
      - qbittorrent
      - nzbget

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /mnt/3TB/docker/Data/radarr/config:/config
      - /mnt/NAS/Media/:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - prowlarr
      - qbittorrent
      - nzbget

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /mnt/3TB/docker/Data/overseerr/config:/config
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "5055:5055"      
    depends_on:
      - radarr
      - sonarr
      - plex

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    runtime: nvidia
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=http://172.20.0.8:32400/
      - PLEX_TRANSCODE_DIR=/transcode
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility

    volumes:
      - /mnt/3TB/docker/Data/plex/config:/config
      - /mnt/3TB/docker/Data/plex/transcode:/transcode
      - /mnt/3TB/docker/Data/plex/transcode/sessions:/transcoding/Transcode/Sessions
      - /mnt/NAS/Media/:/media

    ports:
      - "32400:32400"
    restart: unless-stopped
    networks:
      - backend

  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /mnt/3TB/docker/Data/plex/tautulli:/config
    ports:
      - "8181:8181"
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - plex

networks:
  backend:
    external: true
