services:
  postgresql:
    extends:
      file: ./Authentic-stack.yml
      service: postgresql

  redis:
    extends:
      file: ./Authentic-stack.yml
      service: redis

  worker:
    extends:
      file: ./Authentic-stack.yml
      service: worker

  server:
    extends:
      file: ./Authentic-stack.yml
      service: server

  sonarr:
    extends:
      file: ./dockerfile.yml
      service: sonarr

  emby:
    extends:
      file: ./emby.yml
      service: emby

  wireguard:
    extends:
      file: ./Ez-wireguard.yml
      service: wg-easy

  uptime_kuma:
    extends:
      file: ./UptimeKuma.yml
      service: uptime-kuma
