
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=default
      - GF_SECURITY_ADMIN_PASSWORD=default
    volumes:
      - /mnt/3TB/Docker/Data/logging-stack/grafana_data:/var/lib/grafana
    depends_on:
      - loki
    networks:
      - monitoring

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/loki-config.yaml -config.expand-env=true
    volumes:
      - /mnt/3TB/Docker/Data/logging-stack/loki_config/loki-config.yaml:/etc/loki/loki-config.yaml
    networks:
      - monitoring

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    command: -config.file=/etc/promtail/promtail-config.yaml
    volumes:
      - /mnt/3TB/Docker/Data/logging-stack/promtail_config/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/machine-id:/etc/machine-id:ro
    networks:
      - monitoring

networks:
  monitoring:
