services:
  Sonarr:
    image: linuxserver/sonarr
    container_name: Sonarr
    network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      - UID=1000 # The UID to run emby as (default: 2)
      - GID=100 # The GID to run emby as (default 2)
      - GIDLIST=100 # A comma-separated list of additional GIDs to run emby as (default: 2)
    volumes:
      - /downloads:/mnt/user/appdata/EmbyServer/Sorted/ # Configuration directory
      - /tv:/mnt/disk1/appdata/embydata/
    ports:
      - 8989:8989/tcp # Sonarr web interface
    restart: on-failure
