FROM eclipse-temurin:21-jre-alpine

# Set the working directory
WORKDIR /var/opt

# Install necessary utilities
RUN apk add --no-cache unzip wget

# Download and unzip CrushFTP 11
RUN wget https://www.crushftp.com/early11/CrushFTP11.zip && \
    unzip CrushFTP11.zip && \
    rm CrushFTP11.zip

# Expose required ports
EXPOSE 21 443 2222 8080 9090

# Set the working directory to CrushFTP
WORKDIR /var/opt/CrushFTP11

# Start CrushFTP
CMD ["java", "-Xmx1024m", "-jar", "CrushFTP.jar", "-d"]
